### PR TITLE
Update to Angular 6

### PR DESCRIPTION
**Pull request by FdezRomero**
Hi @edezacas,

I wanted to use ngx-pica on Angular 6 so I forked the repo, updated the dependencies, changed some imports for RxJS 6 and upgraded the build steps with `ng upgrade`.

I thought you might be interested to discuss and merge these changes and eventually publish as 2.0.0 because of the breaking changes on Angular/RxJS 6.

There are other unrelated minimal code changes I found when passing the linter, so I also fixed those warnings while I was at it :wink:

Best,
Rodrigo

### CODE REVIEW

**Comment by edezacas** [comment]
Great, thanks for your job! We're still at angular 5, so too much thanks for this update. Tell us if you detect some bug or performance improvement to fix or apply.

**Comment by FdezRomero** [comment]
Sure thing!

You might want to publish this to npm as `@digitalascetic/ngx-pica@2.0.0`. I would also include a note in the readme explaining to install 1.1.7 for Angular 5 and 2.0.0 for Angular 6.

**Comment by edezacas** [comment]
I've tested pull request and I've received this error:

`TypeError: pica_1.default is not a constructor
    at new NgxPicaService (http://localhost:9876/_karma_webpack_/webpack:/src/ngx-pica.service.ts:14:27)
    at Suite.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/tests/ngx-pica.spec.ts:14:37)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:138:1)
    at Suite.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/jasmine-patch.js:127:1)
    at addSpecsToSuite (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:1107:25)
    at Env.describe (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:1074:7)
    at Env.jasmineEnv.(anonymous function) [as describe] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/jasmine-patch.js:60:1)
    at describe (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:4399:18)
    at Object../tests/ngx-pica.spec.ts (http://localhost:9876/_karma_webpack_/webpack:/tests/ngx-pica.spec.ts:8:1)`

caused by `import pica from 'pica';` 

Are you sure is the correct way to import pica library? if I import as `import * as pica from 'pica';` test is ok. So I'm changed this line.

**Comment by FdezRomero** [comment]
Yes, please revert this to `import * as pica from 'pica';`. You can also change it in the service.

`ts-lint` was suggesting to use the default export and it worked when I published it on npm under `@fdezromero/ngx-pica` to test in an app.

I didn’t notice that this change broke the tests, my bad. It works when installing the package in an Angular app though... 🤔

**Comment by edezacas** [comment]
I've fixed and create the npm package under version 2.0.0

**Comment by FdezRomero** [comment]
👍

**Pull request merged**
